# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "#SaveTheCats"
tagline: "Protect UCLA math cat candidates."
description: "I am a cat ensuring that UCLA math graduate students get their ATC forms processed in a timely manner, so that they are happy cats not sad cats."

# baseurl: # the subpath of your site, e.g. /blog
# url: # the base hostname & protocol for your site
author: Sad cat 1

# analytics
# google_analytics: G-6WD6WQN0QB

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
